name: Scrape and Deploy Volusia County Inmates

on:
  schedule:
    - cron: "0 0,4,9,13,18,22 * * *" # Every 4.5 hours (00:00, 04:30, 09:00, 13:30, 18:00, 22:30 UTC)
  workflow_dispatch: # Allows manual trigger

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Playwright browsers
        run: |
          python -m playwright install
          python -m playwright install-deps

      - name: Run scraper
        run: python volusia.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add volusia_inmates.db
          git commit -m "Update inmate database [skip ci]" || echo "No changes to commit"
          git push https://x:${{ secrets.PAT }}@github.com/gvelasquezneira/volusia_inmates.git || echo "No changes to push"

      - name: Deploy to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: gvelasquezneira.press
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Uploads all files, including volusia_inmates.db
          server-dir: /public_html/  # Adjust to your server's public directory

      - name: Restart Flask service
        uses: appleboy/ssh-action@master
        with:
          host: your-server-ip
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/app
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart your-flask-service
