name: Scrape and Deploy Volusia County Inmates

on:
  schedule:
    - cron: "0 0,4,9,13,18,22 * * *" # Every 4.5 hours
  workflow_dispatch:

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Playwright browsers
        run: |
          python -m playwright install
          python -m playwright install-deps

      - name: Run scraper
        run: python volusia.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add volusia_inmates.db
          git commit -m "Update inmate database [skip ci]" || echo "No changes to commit"
          git push https://x:${{ secrets.PAT }}@github.com/gvelasquezneira/volusia_inmates.git || echo "No changes to push"

      - name: Deploy to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: server326.web-hosting.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/scraping/
          protocol: ftp
          port: 21
      
      - name: Restart Flask service
        uses: appleboy/ssh-action@master
        if: success()
        with:
          host: server326.web-hosting.com
          port: 21098  # Use the SFTP port for SSH connection
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/gvelkjyo/public_html/scraping/
